language: python
python:
  - "3.5"
before_install:
  - mv travis_secrets.yaml secrets.yaml
  - sudo apt-get install -y libudev-dev
  - sudo apt-get install net-tools nmap # For the nmap device tracker integration.
install:
  # Escea custom component
  - pip install escea

  # nmap device integration
  - pip install getmac==0.8.1

  - pip3 install homeassistant
script:
  - hass -c . --script check_config
