# Automations for the porch light. On at sunset, off at sunrise.
# 20200113: i reckon these automations are working just fine.
- id: atSunset-external-lights-on
  alias: 'Porch Light on in the Evening'
  trigger:
  - platform: sun
    event: sunset
  action:
    service: homeassistant.turn_on
    data:
      entity_id: light.exterior_light
- id: atSunrise-external-lights-off
  alias: 'Porch Light off in the Morning'
  trigger:
  - platform: sun
    event: sunrise
  action:
    service: homeassistant.turn_off
    data:
      entity_id: light.exterior_light

# Turn off most lights at midnight. I.e. {Kitchen, Entrance Foyer, Rumpus, Downstairs Hallway, Nursery}.
# The Storeroom and Downstairs Bathroom are on motion sensors, so, who cares. They take care of themselves (for now).
- id: atMidnightAllDownstairsCommonAreaLightsOff
  alias: 'All Downstairs, common-area lights to be turned-off at midnight'
  trigger:
  - platform: time
    at: '00:00:00'
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: group.lights_downstairs_common

# Turn off all master bedroom lights at 0100.
- id: at1amAllMasterBedroomLightsOff
  alias: 'All Master Bedroom lights to be turned-off at 1am each morning'
  trigger:
  - platform: time
    at: '01:00:00'
  action:
    - service: light.turn_off
      data:
        entity_id: light.hue_white_lamp_11
    - service: light.turn_off
      data:
        entity_id: light.hue_white_lamp_9
    - service: switch.turn_off
      data:
        entity_id: switch.bedroom_reading_lamp

# Turn off TV and Roku at 0200.
- id: at2amTvAndRokuOffOff
  alias: 'TV and Roku off at 2am each morning'
  trigger:
  - platform: time
    at: '02:00:00'
  action:
    - service: media_player.turn_off
      data:
        entity_id: media_player.lg_webos_smart_tv
    - service: media_player.turn_off
      data:
        entity_id: media_player.roku_yl00at185320

# During evening time, lights on downstairs when anyone arrives home {Kitchen, Entrance Foyer, Rumpus, Downstairs Hallway}.
# During daytime, lights on downstairs when the first person arrives home.
# TODO: correct to match the written use case.
#   ANSWER: I think this is now done.
# TODO: add a delay. E.g. have to be gone for 5 mins as a condition.
#   ANSWER: this is to avoid flapping, I think. Is it required?
# TODO: will this logic work if Emma and I both arrive home simultaneously?
#   ANSWER: I think it will. Unless we arrive at the very same second AND it's daytime. In which case - the conditions will
#           halt execution. Do I care? I don't think so? Night time arrivals will still work.
#
# 20200119: using the someone_home sensor. This of course strands the "any arrival during nighttime" use case.
# 20200120: the daytime element is now done, and we now need a separate automation for daytime arrivals.
- id: onFirstPersonHomeTurnDownstairsLightsOn
  alias: "Arrival lights for the first person arriving home."
  trigger:
  - platform: state
    entity_id: sensor.someone_home
    from: 'Unoccupied'
    to: 'Occupied'
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: group.lights_downstairs_common

- id: onAnyArrivalAfterSunsetTurnDownstairsLightsOn
  alias: "Arrival lights for any arrival after sunset, without regard to occupancy."
  trigger:
  - platform: state
    entity_id: person.emma
    from: 'not_home'
    to: 'home'
  - platform: state
    entity_id: person.pete
    from: 'not_home'
    to: 'home'
  condition:
    condition: state  # from sunset until sunrise
    entity_id: sun.sun
    state: 'below_horizon'
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: group.lights_downstairs_common

# lights off downstairs when the last person leaves home {Kitchen, Entrance Foyer, Rumpus, Downstairs Hallway}.
# 20200113: I don't reckon this is working now. I think it gets down to my complicating the state machines.
# is home -> not_home really the way to go? Perhaps not. I should experiment with firing events in Dev Tools, and set the states.
#
# 20200119: changed to utilise the someone_home sensor.
- id: onLastPersonLeavesTurnDownstairsLightsOff
  alias: "Lights off when the last person leaves home"
  trigger:
  - platform: state
    entity_id: sensor.someone_home
    from: 'Occupied'
    to: 'Unoccupied'
    for:
      minutes: 10
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: group.lights_downstairs_common

# Credit where it's due:
# https://community.home-assistant.io/t/a-backup-tool-with-automated-schedule-excluding-db-files-since-they-are-usually-large/99924/4
- id: at3amTriggerFullSnapshot
  alias: "Hassio Snapshot daily at 3am."
  initial_state: 'on'
  trigger:
  - platform: time
    at: '03:00:00'
  condition: []
  action:
    - service: hassio.snapshot_full
      data_template:
        name: Automated Backup {{ now().strftime('%Y-%m-%d') }}

- id: at4amTriggerDropboxSync
  alias: "Dropbox backup sync daily at 4am."
  initial_state: 'on'
  trigger:
  - platform: time
    at: '04:00:00'
  condition: []
  action:
    - service: hassio.addon_stdin
      data_template:
        addon: 7be23ff5_dropbox_sync
        input: {"command":"upload"}

- id: delayHomekitStartUntilKasaComponentsBoot
  alias: 'Delay the Homekit service from starting until Kasa components are up'
  trigger:
  - platform: homeassistant
    event: start
  action:
    - wait_template: >-
        {% if not states.switch.kitchen_lighting_strip %}
          false
        {% elif not states.switch.bedroom_reading_lamp %}
          false
        {% else %}
          true
        {% endif %}
      timeout: 00:15  # Waits 15 minutes
      continue_on_timeout: false
    - service: homekit.start

# TODO: lights on / off in response to motion detection in bathroom, in storeroom, in downstairs corridor.

- id: alarmMovementInEaves
  alias: 'Notify Pete\'s iPhone if movement is detected in the Eaves'
  trigger:
    - platform: state
      entity_id: binary_sensor.eaves_sensor_motion
      to: "Detected"
  action:
    - service: notify.mobile_app_steve_jobs_iphone_3g
      data:
        title: "Motion Alarm"
        message: "Motion detected in: the Eaves."
