# Automations for the porch light. On at sunset, off at sunrise.
# 20200113: i reckon these automations are working just fine.
- id: atSunset-external-lights-on
  alias: 'Porch Light on in the Evening'
  trigger:
  - platform: sun
    event: sunset
  action:
    service: homeassistant.turn_on
    data:
      entity_id: light.exterior_light
- id: atSunrise-external-lights-off
  alias: 'Porch Light off in the Morning'
  trigger:
  - platform: sun
    event: sunrise
  action:
    service: homeassistant.turn_off
    data:
      entity_id: light.exterior_light

# Turn off most lights at midnight. I.e. {Kitchen, Entrance Foyer, Rumpus, Downstairs Hallway, Nursery}.
# The Storeroom and Downstairs Bathroom are on motion sensors, so, who cares. They take care of themselves (for now).
- id: atMidnightAllDownstairsCommonAreaLightsOff
  alias: 'All Downstairs, common-area lights to be turned-off at midnight'
  trigger:
  - platform: time
    at: '00:00:00'
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: group.lights_downstairs_common

# Turn off all master bedroom lights at 0100.
- id: at1amAllMasterBedroomLightsOff
  alias: 'All Master Bedroom lights to be turned-off at 1am each morning'
  trigger:
  - platform: time
    at: '01:00:00'
  action:
    - service: light.turn_off
      data:
        entity_id: light.hue_white_lamp_11
    - service: light.turn_off
      data:
        entity_id: light.hue_white_lamp_9
    - service: switch.turn_off
      data:
        entity_id: switch.bedroom_reading_lamp

# Turn off TV and Roku at 0200.
- id: at2amTvAndRokuOffOff
  alias: 'TV and Roku off at 2am each morning'
  trigger:
  - platform: time
    at: '02:00:00'
  action:
    - service: media_player.turn_off
      data:
        entity_id: media_player.lg_webos_smart_tv
    - service: media_player.turn_off
      data:
        entity_id: media_player.roku_yl00at185320

# During evening time, lights on downstairs when anyone arrives home {Kitchen, Entrance Foyer, Rumpus, Downstairs Hallway}.
# During daytime, lights on downstairs when the first person arrives home.
# TODO: correct to match the written use case.
#   ANSWER: I think this is now done.
# TODO: add a delay. E.g. have to be gone for 5 mins as a condition.
#   ANSWER: this is to avoid flapping, I think. Is it required?
# TODO: will this logic work if Emma and I both arrive home simultaneously?
#   ANSWER: I think it will. Unless we arrive at the very same second AND it's daytime. In which case - the conditions will
#           halt execution. Do I care? I don't think so? Night time arrivals will still work.
- id: onFirstPersonHomeTurnDownstairsLightsOn
  alias: "Arrival lights for the first person arriving home, or any arrival after sunset"
  trigger:
  - platform: state
    entity_id: person.emma
    from: 'not_home'
    to: 'home'
  - platform: state
    entity_id: person.pete
    from: 'not_home'
    to: 'home'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: and
        conditions:
          - condition: state
            entity_id: sun.sun
            state: 'above_horizon'
          - condition: or
            conditions:
              - condition: state
                entity_id: person.emma
                state: 'not_home'
              - condition: state
                entity_id: person.pete
                state: 'not_home'
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: group.lights_downstairs_common

# lights off downstairs when the last person leaves home {Kitchen, Entrance Foyer, Rumpus, Downstairs Hallway}.
# 20200113: I don't reckon this is working now. I think it gets down to my complicating the state machines.
# is home -> not_home really the way to go? Perhaps not. I should experiment with firing events in Dev Tools, and set the states.
- id: onLastPersonLeavesTurnDownstairsLightsOff
  alias: "Lights off when the last person leaves home"
  # So, the trigger is - either person leaves and stays gone for 10 mins.
  # I wonder whether 'not_home' is the correct literal to use. What about when I have other zones like 'work'.
  # What I want is !('home'). Unless 'not_home' achieves the same thing.
  #
  # Apparently I can indeed rely on 'not_home': https://community.home-assistant.io/t/location-not-home-vs-away/70050/6
  #
  trigger:
  - platform: state
    entity_id: person.emma
    from: 'home'
    to: 'not_home'
    for:
      minutes: 10
  - platform: state
    entity_id: person.pete
    from: 'home'
    to: 'not_home'
    for:
      minutes: 10
  # 20200114: the way this is written - the person that's already left - has to have been gone for 5 mins. So, this is a flaw
  # in my view. What happens if we both leave at the same time. Or, more accurately < 5 mins apart from each other. In this case
  # the condition will interdict the trigger - and that's it - the trigger will never fire again.
  #
  # So, what's the danger if I remove the time restriction? What was I trying to protect?
  #
  # I think we will the condition for the other person to have also been gone for 5 mins, and see what happens.
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: person.emma
      state: 'not_home'
    - condition: state
      entity_id: person.pete
      state: 'not_home'
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: group.lights_downstairs_common

# TODO: lights on / off in response to motion detection in bathroom, in storeroom, in downstairs corridor.
