# Automations for the porch light. On at sunset, off at sunrise.
- id: atSunset-external-lights-on
  alias: 'Porch Light on in the Evening'
  trigger:
  - platform: sun
    event: sunset
  action:
    service: homeassistant.turn_on
    data:
      entity_id: light.exterior_light
- id: atSunrise-external-lights-off
  alias: 'Porch Light off in the Morning'
  trigger:
  - platform: sun
    event: sunrise
  action:
    service: homeassistant.turn_off
    data:
      entity_id: light.exterior_light

# Turn off most lights at midnight. I.e. {Kitchen, Entrance Foyer, Rumpus, Downstairs Hallway, Nursery}.
# The Storeroom and Downstairs Bathroom are on motion sensors, so, who cares. They take care of themselves (for now).
- id: atMidnightAllDownstairsCommonAreaLightsOff
  alias: 'All Downstairs, common-area lights to be turned-off at midnight'
  trigger:
  - platform: time
    at: '00:00:00'
  action:
    - service: light.turn_off
      data:
        entity_id: light.hue_color_lamp   # Downstairs hallway
    - service: light.turn_off
      data:
        entity_id: light.hue_white_lamp_2 # Downstairs hallway
    - service: light.turn_off
      data:
        entity_id: light.hue_white_lamp_3 # Downstairs hallway
    - service: light.turn_off
      data:
        entity_id: light.hue_white_lamp_1 # Entrance foyer
    - service: light.turn_off
      data:
        entity_id: light.hue_white_lamp_4 # Kitchen
    - service: light.turn_off
      data:
        entity_id: light.hue_white_lamp_5 # Kitchen
    - service: light.turn_off
      data:
        entity_id: light.hue_white_lamp_6 # Rumpus
    - service: light.turn_off
      data:
        entity_id: light.hue_white_lamp_7  # Rumpus        
    - service: light.turn_off
      data:
        entity_id: light.hue_white_lamp_12 # Nursey
    - service: switch.turn_off
      data:
        entity_id: switch.kitchen_lighting_strip

# Turn off all master bedroom lights at 0100.
- id: at1amAllMasterBedroomLightsOff
  alias: 'All Master Bedroom lights to be turned-off at 1am each morning'
  trigger:
  - platform: time
    at: '01:00:00'
  action:
    - service: light.turn_off
      data:
        entity_id: light.hue_white_lamp_11
    - service: light.turn_off
      data:
        entity_id: light.hue_white_lamp_9
    - service: switch.turn_off
      data:
        entity_id: switch.reading_lamp

# Turn off TV and Roku at 0200.
- id: at2amTvAndRokuOffOff
  alias: 'TV and Roku off at 2am each morning'
  trigger:
  - platform: time
    at: '02:00:00'
  action:
    - service: media_player.turn_off
      data:
        entity_id: media_player.lg_webos_smart_tv
    - service: media_player.turn_off
      data:
        entity_id: media_player.roku_yl00at185320


# During evening time, lights on downstairs when anyone arrives home {Kitchen, Entrance Foyer, Rumpus, Downstairs Hallway}.
# During daytime, lights on downstairs when the first person arrives home.
# TODO: correct to match the written use case.
# TODO: add a delay. E.g. have to be gone for 5 mins as a condition.
# TODO: will this logic work if Emma and I both arrive home simultaneously?
- id: onFirstPersonHomeTurnDownstairsLightsOn
  alias: "Arrival lights for the first person arriving home, or any arrival after sunset"
  trigger:
  - platform: state
    entity_id: person.emma_wills
    from: 'not_home'
    to: 'home'
  - platform: state
    entity_id: person.pete_wills
    from: 'not_home'
    to: 'home'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: and
        conditions:
          - condition: state
            entity_id: sun.sun
            state: 'above_horizon'
          - condition: or
            conditions:
              - condition: state
                entity_id: person.emma_wills
                state: 'not_home'
              - condition: state
                entity_id: person.pete_wills
                state: 'not_home'
  action:
    - service: light.turn_on
      data:
        entity_id: light.hue_color_lamp   # Downstairs hallway
    - service: light.turn_on
      data:
        entity_id: light.hue_white_lamp_2 # Downstairs hallway
    - service: light.turn_on
      data:
        entity_id: light.hue_white_lamp_3 # Downstairs hallway
    - service: light.turn_on
      data:
        entity_id: light.hue_white_lamp_1 # Entrance foyer
    - service: light.turn_on
      data:
        entity_id: light.hue_white_lamp_4 # Kitchen
    - service: light.turn_on
      data:
        entity_id: light.hue_white_lamp_5 # Kitchen
    - service: light.turn_on
      data:
        entity_id: light.hue_white_lamp_6 # Rumpus
    - service: light.turn_on
      data:
        entity_id: light.hue_white_lamp_7  # Rumpus        
    - service: light.turn_on
      data:
        entity_id: light.hue_white_lamp_12 # Nursey
    - service: switch.turn_on
      data:
        entity_id: switch.kitchen_lighting_strip

# lights off downstairs when the last person leaves home {Kitchen, Entrance Foyer, Rumpus, Downstairs Hallway}.
- id: onLastPersonLeavesTurnDownstairsLightsOff
  alias: "Lights off when the last person leaves home"
  trigger:
  - platform: state
    entity_id: person.emma_wills
    from: 'home'
    to: 'not_home'
    for:
      minutes: 10
  - platform: state
    entity_id: person.pete_wills
    from: 'home'
    to: 'not_home'
    for:
      minutes: 10
  condition: 
    condition: and
    conditions:
    - condition: state
      entity_id: person.emma_wills
      state: 'not_home'
    - condition: state
      entity_id: person.pete_wills
      state: 'not_home'
    - condition: template
      value_template: >
        {{ (as_timestamp(now()) - as_timestamp(states.person.emma_wills.last_changed)) > 300 }}
    - condition: template
      value_template: >
        {{ (as_timestamp(now()) - as_timestamp(states.person.pete_wills.last_changed)) > 300 }}      
  action:
    - service: light.turn_off
      data:
        entity_id: light.hue_color_lamp   # Downstairs hallway
    - service: light.turn_off
      data:
        entity_id: light.hue_white_lamp_2 # Downstairs hallway
    - service: light.turn_off
      data:
        entity_id: light.hue_white_lamp_3 # Downstairs hallway
    - service: light.turn_off
      data:
        entity_id: light.hue_white_lamp_1 # Entrance foyer
    - service: light.turn_off
      data:
        entity_id: light.hue_white_lamp_4 # Kitchen
    - service: light.turn_off
      data:
        entity_id: light.hue_white_lamp_5 # Kitchen
    - service: light.turn_off
      data:
        entity_id: light.hue_white_lamp_6 # Rumpus
    - service: light.turn_off
      data:
        entity_id: light.hue_white_lamp_7  # Rumpus        
    - service: light.turn_off
      data:
        entity_id: light.hue_white_lamp_12 # Nursey
    - service: switch.turn_off
      data:
        entity_id: switch.kitchen_lighting_strip

# TODO: lights on / off in response to motion detection in bathroom, in storeroom, in downstairs corridor.
