- id: atSunset-external-lights-on
  alias: 'Porch Light on in the Evening'
  trigger:
  - platform: sun
    event: sunset
  action:
    service: homeassistant.turn_on
    entity_id: light.exterior_light
- id: atSunrise-external-lights-off
  alias: 'Porch Light off in the Morning'
  trigger:
  - platform: sun
    event: sunrise
  action:
    service: homeassistant.turn_off
    entity_id: light.exterior_light
