homeassistant:
  name: Home
  longitude: !secret zone_home_long
  latitude: !secret zone_home_lat
  elevation: 96
  unit_system: metric
  time_zone: Australia/Hobart
  customize:
    person.Emma:
      entity_picture: "/local/74237625_10157294660205528_155584236814860288_n.jpg"
    person.Pete:
      entity_picture: "/local/1973924_10152352571083092_1135754224_o.jpg"
  packages: !include_dir_named packages

default_config:

camera:
  - platform: bom
    id: '372'
    delta: 600
    frames: 4

#climate:
#  - platform: escea

device_tracker:
  - platform: nmap_tracker
    hosts:
      192.168.0.104
      192.168.0.105
      192.168.0.106
      192.168.0.112
      192.168.0.113
    home_interval: 1
    consider_home: 240
  - platform: bluetooth_tracker
  - platform: tile
    username: !secret tile_username
    password: !secret tile_password

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret
  track_new_calendar: false

homekit:
  auto_start: false
  safe_mode: false
  filter:
    include_entities:
      - switch.kitchen_lighting_strip
      - switch.bedroom_reading_lamp

input_boolean:
  boolean_evie_sleep_mode:
    name: boolean indicating whether or not Sleep Mode is on.
  boolean_occupancy_guest_mode:
    name: boolean indicating whether or not Guest Mode is on.

input_datetime:
  datetime_last_alerted_motion_anywhere_unoccupied:
    name: datetime last alert sent for motion detected anywhere, when Unoccupied
    has_date: true
    has_time: true
  datetime_last_alerted_motion_eaves:
    name: datetime last alert sent for motion detected in the Eaves
    has_date: true
    has_time: true
  datetime_last_alerted_motion_evie_sleep_mode:
    name: datetime last alert sent for motion detected during Sleep Mode
    has_date: true
    has_time: true


ios:

logger:
  default: critical
  logs:
    custom_components.escea: debug

lovelace:
  mode: yaml

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

notify:
  - name: petes_ios_devices
    platform: group
    services:
      - service: mobile_app_steve_jobs_iphone_3g
      - service: mobile_app_pete_wills_ipad

person:
  - name: Pete
    id: 9171f88c29f143e9a2a2f5ea2890339d
    device_trackers:
      - device_tracker.petes_iphone_bt
      - device_tracker.petes_iphone_gps
      - device_tracker.petes_iphone_wifi
#      - device_tracker.tile_e4dd14420d344e34
  - name: Emma
    id: 6Y7i2MHyeedbkHT7o$sZ&bPOyk7f1guQ
    device_trackers:
      - device_tracker.emmas_iphone_bt
      - device_tracker.emmas_iphone_wifi

recorder:

roku:
  - host: 192.168.0.123

tts:
  - platform: google_translate

weather:
  - platform: bom
    station: IDT60801.94970
  - platform: darksky
    api_key: !secret bom_api_key
    mode: daily
    latitude: !secret zone_home_lat
    longitude: !secret zone_home_long

webostv:
    host: 192.168.0.121
    #other settings
    turn_on_action:
        service: wake_on_lan.send_magic_packet
        data:
          mac: "00:00:00:00:00:00"

# Includes
automation: !include automations.yaml
group: !include groups.yaml
logbook: !include logbook.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
zone: !include zone.yaml
