homeassistant:
  name: Home
  longitude: !secret zone_home_long
  latitude: !secret zone_home_lat
  elevation: 96
  unit_system: metric
  time_zone: Australia/Hobart
  customize:
    person.Emma:
      entity_picture: "/local/74237625_10157294660205528_155584236814860288_n.jpg"
    person.Pete:
      entity_picture: "/local/1973924_10152352571083092_1135754224_o.jpg"
  packages: !include_dir_named packages

default_config:

tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# Attempt to pair homekit without recourse to HomeBridge 20200108.
# I just want the TP-Link elements.
homekit:
  auto_start: false
  safe_mode: false
  filter:
    include_entities:
      - switch.kitchen_lighting_strip
      - switch.bedroom_reading_lamp

# Nest seems stable as of 20190831. Fingers-crossed.
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

# This is the BoM block. Working ok in Test.
weather:
  - platform: bom
    station: IDT60801.94970
  - platform: darksky
    api_key: !secret bom_api_key
    mode: daily
    latitude: !secret zone_home_lat
    longitude: !secret zone_home_long

camera:
  - platform: bom
    id: '372'
    delta: 600
    frames: 4

sensor:
  - platform: github
    access_token: !secret travisci_api_key
    repositories:
      - path: 'pa-wills/Home-Assistant-Config'
  - platform: travisci
    api_key: !secret travisci_api_key
    branch: 'master'
  - platform: uptime
    name: Time Online
    unit_of_measurement: hours
  - platform: bom
    monitored_conditions:
      - apparent_t
      - cloud
      - cloud_base_m
      - cloud_oktas
      - cloud_type_id
      - cloud_type
      - delta_t
      - gust_kmh
      - gust_kt
      - air_temp
      - dewpt
      - local_date_time
      - local_date_time_full
      - press
      - press_qnh
      - press_msl
      - press_tend
      - rain_trace
      - rel_hum
      - sea_state
      - swell_dir_worded
      - swell_height
      - swell_period
      - vis_km
      - weather
      - wind_dir
      - wind_spd_kmh
      - wind_spd_kt
    station: IDT60801.94970
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: swap_use_percent
      - type: processor_use
      - type: last_boot
      - type: load_1m
      - type: load_5m
      - type: load_15m
  - platform: darksky
    api_key: !secret darksky_api_key
    forecast:
      - 1
      - 2
      - 3
      - 4
      - 5
    monitored_conditions:
      - icon
      - summary
      - nearest_storm_distance
      - nearest_storm_bearing
      - humidity
      - temperature
      - temperature_high
      - temperature_low
      - apparent_temperature
      - apparent_temperature_high
      - apparent_temperature_low
      - wind_speed
      - wind_bearing
      - precip_type
      - precip_probability
      - precip_accumulation
      - precip_intensity
      - precip_intensity_max
      - uv_index
      - daily_summary
      - pressure
      - visibility
  - platform: template
    sensors:
      someone_home:
        friendly_name: Someone Home
        icon_template: >-
          {% if is_state('binary_sensor.someone_home','on') %}
            mdi:home-account
          {% else %}
            mdi:home-outline
          {% endif %}
        value_template: "{{ is_state('person.emma','home') or  is_state('person.pete','home') }}"

# Tracking stuff
device_tracker:
  - platform: nmap_tracker
    hosts:
      192.168.0.104
      192.168.0.105
      192.168.0.106
      192.168.0.112
      192.168.0.113
    home_interval: 1
    consider_home: 240
  - platform: bluetooth_tracker
  - platform: tile
    username: !secret tile_username
    password: !secret tile_password

person:
  - name: Pete
    id: 9171f88c29f143e9a2a2f5ea2890339d
    device_trackers:
      - device_tracker.steve_jobs_iphone_3g
      - device_tracker.tile_e4dd14420d344e34
  - name: Emma
    id: 6Y7i2MHyeedbkHT7o$sZ&bPOyk7f1guQ
    device_trackers:
      - device_tracker.emma_s_iphone



zone:
  - name: Home
    latitude: !secret zone_home_lat
    longitude: !secret zone_home_long
    radius: 50
    icon: mdi:home

  - name: School
    latitude: !secret zone_school_lat
    longitude: !secret zone_school_long
    radius: 30
    icon: mdi:school

  - name: Shop
    latitude: !secret zone_shop_lat
    longitude: !secret zone_shop_long
    radius: 30
    icon: mdi:worker

  - name: Work
    latitude: !secret zone_work_lat
    longitude: !secret zone_work_long
    radius: 30
    icon: mdi:worker

ios:

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret
  track_new_calendar: false

lovelace:
  mode: yaml

#climate:
#  - platform: escea

# Trying to make this less chatty. Domain exclusions seem insufficient.
# Thus, we need to get exhaustive, it seems.
logbook:
  exclude:
    domains:
      - weather
    entities:
      - sensor.bom_air_temp_c
      - sensor.bom_cloud
      - sensor.bom_cloud_base
      - sensor.bom_cloud_oktas
      - sensor.bom_cloud_type
      - sensor.bom_cloud_type_id
      - sensor.bom_delta_temp_c
      - sensor.bom_dew_point_c
      - sensor.bom_feels_like_c
      - sensor.bom_local_time
      - sensor.bom_local_time_full
      - sensor.bom_pressure_mb
      - sensor.bom_pressure_msl
      - sensor.bom_pressure_qnh
      - sensor.bom_pressure_tend
      - sensor.bom_rain_today
      - sensor.bom_relative_humidity
      - ensor.bom_sea_state
      - sensor.bom_swell_direction
      - sensor.bom_swell_height
      - sensor.bom_swell_period
      - sensor.bom_visability_km
      - sensor.bom_weather
      - sensor.bom_wind_direction
      - sensor.bom_wind_gust_kmh
      - sensor.bom_wind_gust_kt
      - sensor.bom_wind_speed_kmh
      - sensor.bom_wind_speed_kt
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_daily_max_precip_intensity_1d
      - sensor.dark_sky_daily_max_precip_intensity_2d
      - sensor.dark_sky_daily_max_precip_intensity_3d
      - sensor.dark_sky_daily_max_precip_intensity_4d
      - sensor.dark_sky_daily_max_precip_intensity_5d
      - sensor.dark_sky_daily_summary
      - sensor.dark_sky_daytime_high_apparent_temperature_1d
      - sensor.dark_sky_daytime_high_apparent_temperature_2d
      - sensor.dark_sky_daytime_high_apparent_temperature_3d
      - sensor.dark_sky_daytime_high_apparent_temperature_4d
      - sensor.dark_sky_daytime_high_apparent_temperature_5d
      - sensor.dark_sky_daytime_high_temperature_1d
      - sensor.dark_sky_daytime_high_temperature_2d
      - sensor.dark_sky_daytime_high_temperature_3d
      - sensor.dark_sky_daytime_high_temperature_4d
      - sensor.dark_sky_daytime_high_temperature_5d
      - sensor.dark_sky_humidity
      - sensor.dark_sky_humidity_1d
      - sensor.dark_sky_humidity_2d
      - sensor.dark_sky_humidity_3d
      - sensor.dark_sky_humidity_4d
      - sensor.dark_sky_humidity_5d
      - sensor.dark_sky_icon
      - sensor.dark_sky_icon_1d
      - sensor.dark_sky_icon_2d
      - sensor.dark_sky_icon_3d
      - sensor.dark_sky_icon_4d
      - sensor.dark_sky_icon_5d
      - sensor.dark_sky_nearest_storm_bearing
      - sensor.dark_sky_nearest_storm_distance
      - sensor.dark_sky_overnight_low_apparent_temperature_1d
      - sensor.dark_sky_overnight_low_apparent_temperature_2d
      - sensor.dark_sky_overnight_low_apparent_temperature_3d
      - sensor.dark_sky_overnight_low_apparent_temperature_4d
      - sensor.dark_sky_overnight_low_apparent_temperature_5d
      - sensor.dark_sky_overnight_low_temperature_1d
      - sensor.dark_sky_overnight_low_temperature_2d
      - sensor.dark_sky_overnight_low_temperature_3d
      - sensor.dark_sky_overnight_low_temperature_4d
      - sensor.dark_sky_overnight_low_temperature_5d
      - sensor.dark_sky_precip
      - sensor.dark_sky_precip_1d
      - sensor.dark_sky_precip_2d
      - sensor.dark_sky_precip_3d
      - sensor.dark_sky_precip_4d
      - sensor.dark_sky_precip_5d
      - sensor.dark_sky_precip_accumulation_1d
      - sensor.dark_sky_precip_accumulation_2d
      - sensor.dark_sky_precip_accumulation_3d
      - sensor.dark_sky_precip_accumulation_4d
      - sensor.dark_sky_precip_accumulation_5d
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_precip_intensity_1d
      - sensor.dark_sky_precip_intensity_2d
      - sensor.dark_sky_precip_intensity_3d
      - sensor.dark_sky_precip_intensity_4d
      - sensor.dark_sky_precip_intensity_5d
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_precip_probability_1d
      - sensor.dark_sky_precip_probability_2d
      - sensor.dark_sky_precip_probability_3d
      - sensor.dark_sky_precip_probability_4d
      - sensor.dark_sky_precip_probability_5d
      - sensor.dark_sky_pressure
      - sensor.dark_sky_pressure_1d
      - sensor.dark_sky_pressure_2d
      - sensor.dark_sky_pressure_3d
      - sensor.dark_sky_pressure_4d
      - sensor.dark_sky_pressure_5d
      - sensor.dark_sky_summary
      - sensor.dark_sky_summary_1d
      - sensor.dark_sky_summary_2d
      - sensor.dark_sky_summary_3d
      - sensor.dark_sky_summary_4d
      - sensor.dark_sky_summary_5d
      - sensor.dark_sky_temperature
      - sensor.dark_sky_uv_index
      - sensor.dark_sky_uv_index_1d
      - sensor.dark_sky_uv_index_2d
      - sensor.dark_sky_uv_index_3d
      - sensor.dark_sky_uv_index_4d
      - sensor.dark_sky_uv_index_5d
      - sensor.dark_sky_visibility
      - sensor.dark_sky_visibility_1d
      - sensor.dark_sky_visibility_2d
      - sensor.dark_sky_visibility_3d
      - sensor.dark_sky_visibility_4d
      - sensor.dark_sky_visibility_5d
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_wind_bearing_1d
      - sensor.dark_sky_wind_bearing_2d
      - sensor.dark_sky_wind_bearing_3d
      - sensor.dark_sky_wind_bearing_4d
      - sensor.dark_sky_wind_bearing_5d
      - sensor.dark_sky_wind_speed
      - sensor.dark_sky_wind_speed_1d
      - sensor.dark_sky_wind_speed_2d
      - sensor.dark_sky_wind_speed_3d
      - sensor.dark_sky_wind_speed_4d
      - sensor.dark_sky_wind_speed_5d

logger:
  default: info
  logs:
    custom_components.escea: debug

media_player:
  - platform: webostv
    host: 192.168.0.121
    turn_on_action:
      service: wake_on_lan.send_magic_packet
roku:
  - host: 192.168.0.123
