homeassistant:
  name: Home
  longitude: !secret zone_home_long
  latitude: !secret zone_home_lat
  elevation: 96
  unit_system: metric
  time_zone: Australia/Hobart
  customize:
    person.Emma:
      entity_picture: "/local/74237625_10157294660205528_155584236814860288_n.jpg"
    person.Pete:
      entity_picture: "/local/1973924_10152352571083092_1135754224_o.jpg"
  packages: !include_dir_named packages

default_config:

camera:
  - platform: bom
    id: '372'
    delta: 600
    frames: 4

#climate:
#  - platform: escea

device_tracker:
  - platform: nmap_tracker
    hosts:
      192.168.0.104
      192.168.0.105
      192.168.0.106
      192.168.0.112
      192.168.0.113
    home_interval: 1
    consider_home: 240
  - platform: bluetooth_tracker
  - platform: tile
    username: !secret tile_username
    password: !secret tile_password

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret
  track_new_calendar: false

homekit:
  auto_start: false
  safe_mode: false
  filter:
    include_entities:
      - switch.kitchen_lighting_strip
      - switch.bedroom_reading_lamp

ios:

logger:
  default: info
  logs:
    custom_components.escea: debug

lovelace:
  mode: yaml

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

person:
  - name: Pete
    id: 9171f88c29f143e9a2a2f5ea2890339d
    device_trackers:
      - device_tracker.petes_iphone
      - device_tracker.petes_keys
  - name: Emma
    id: 6Y7i2MHyeedbkHT7o$sZ&bPOyk7f1guQ
    device_trackers:
      - device_tracker.emmas_iphone

roku:
  - host: 192.168.0.123

tts:
  - platform: google_translate

weather:
  - platform: bom
    station: IDT60801.94970
  - platform: darksky
    api_key: !secret bom_api_key
    mode: daily
    latitude: !secret zone_home_lat
    longitude: !secret zone_home_long

webostv:
  host: 192.168.0.121
  #other settings
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: "00:00:00:00:00:00"
    standby_connection: true

# Includes
automation: !include automations.yaml
group: !include groups.yaml
logbook: !include logbook.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
zone: !include zone.yaml
