homeassistant:
  name: Home
  longitude: !secret zone_home_long
  latitude: !secret zone_home_lat
  elevation: !secret zone_home_elevation
  unit_system: metric
  time_zone: Australia/Hobart
  customize:
    person.Emma:
      entity_picture: "/local/74237625_10157294660205528_155584236814860288_n.jpg"
    person.Pete:
      entity_picture: "/local/1973924_10152352571083092_1135754224_o.jpg"
  packages: !include_dir_named packages

default_config:

#climate:
#  - platform: escea

clean_up_snapshots_service:
  host: !secret clos_base_url
  token: !secret clos_clean_up_token
  number_of_snapshots_to_keep: 3

device_tracker:
  - platform: nmap_tracker
    hosts:
      192.168.0.104
      192.168.0.105
      192.168.0.106
      192.168.0.112
      192.168.0.113
    home_interval: 1
    consider_home: 240
  - platform: bluetooth_tracker
  - platform: tile
    username: !secret tile_username
    password: !secret tile_password

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret
  track_new_calendar: false

history:
  exclude:
    domains:
      - automation
      - input_datetime
      - script
    entities:
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_daily_max_precip_intensity_1d
      - sensor.dark_sky_daily_max_precip_intensity_2d
      - sensor.dark_sky_daily_max_precip_intensity_3d
      - sensor.dark_sky_daily_max_precip_intensity_4d
      - sensor.dark_sky_daily_max_precip_intensity_5d
      - sensor.dark_sky_daily_summary
      - sensor.dark_sky_daytime_high_apparent_temperature_1d
      - sensor.dark_sky_daytime_high_apparent_temperature_2d
      - sensor.dark_sky_daytime_high_apparent_temperature_3d
      - sensor.dark_sky_daytime_high_apparent_temperature_4d
      - sensor.dark_sky_daytime_high_apparent_temperature_5d
      - sensor.dark_sky_daytime_high_temperature_1d
      - sensor.dark_sky_daytime_high_temperature_2d
      - sensor.dark_sky_daytime_high_temperature_3d
      - sensor.dark_sky_daytime_high_temperature_4d
      - sensor.dark_sky_daytime_high_temperature_5d
      - sensor.dark_sky_humidity
      - sensor.dark_sky_humidity_1d
      - sensor.dark_sky_humidity_2d
      - sensor.dark_sky_humidity_3d
      - sensor.dark_sky_humidity_4d
      - sensor.dark_sky_humidity_5d
      - sensor.dark_sky_icon
      - sensor.dark_sky_icon_1d
      - sensor.dark_sky_icon_2d
      - sensor.dark_sky_icon_3d
      - sensor.dark_sky_icon_4d
      - sensor.dark_sky_icon_5d
      - sensor.dark_sky_nearest_storm_bearing
      - sensor.dark_sky_nearest_storm_distance
      - sensor.dark_sky_overnight_low_apparent_temperature_1d
      - sensor.dark_sky_overnight_low_apparent_temperature_2d
      - sensor.dark_sky_overnight_low_apparent_temperature_3d
      - sensor.dark_sky_overnight_low_apparent_temperature_4d
      - sensor.dark_sky_overnight_low_apparent_temperature_5d
      - sensor.dark_sky_overnight_low_temperature_1d
      - sensor.dark_sky_overnight_low_temperature_2d
      - sensor.dark_sky_overnight_low_temperature_3d
      - sensor.dark_sky_overnight_low_temperature_4d
      - sensor.dark_sky_overnight_low_temperature_5d
      - sensor.dark_sky_precip
      - sensor.dark_sky_precip_1d
      - sensor.dark_sky_precip_2d
      - sensor.dark_sky_precip_3d
      - sensor.dark_sky_precip_4d
      - sensor.dark_sky_precip_5d
      - sensor.dark_sky_precip_accumulation_1d
      - sensor.dark_sky_precip_accumulation_2d
      - sensor.dark_sky_precip_accumulation_3d
      - sensor.dark_sky_precip_accumulation_4d
      - sensor.dark_sky_precip_accumulation_5d
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_precip_intensity_1d
      - sensor.dark_sky_precip_intensity_2d
      - sensor.dark_sky_precip_intensity_3d
      - sensor.dark_sky_precip_intensity_4d
      - sensor.dark_sky_precip_intensity_5d
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_precip_probability_1d
      - sensor.dark_sky_precip_probability_2d
      - sensor.dark_sky_precip_probability_3d
      - sensor.dark_sky_precip_probability_4d
      - sensor.dark_sky_precip_probability_5d
      - sensor.dark_sky_pressure
      - sensor.dark_sky_pressure_1d
      - sensor.dark_sky_pressure_2d
      - sensor.dark_sky_pressure_3d
      - sensor.dark_sky_pressure_4d
      - sensor.dark_sky_pressure_5d
      - sensor.dark_sky_summary
      - sensor.dark_sky_summary_1d
      - sensor.dark_sky_summary_2d
      - sensor.dark_sky_summary_3d
      - sensor.dark_sky_summary_4d
      - sensor.dark_sky_summary_5d
      - sensor.dark_sky_temperature
      - sensor.dark_sky_uv_index
      - sensor.dark_sky_uv_index_1d
      - sensor.dark_sky_uv_index_2d
      - sensor.dark_sky_uv_index_3d
      - sensor.dark_sky_uv_index_4d
      - sensor.dark_sky_uv_index_5d
      - sensor.dark_sky_visibility
      - sensor.dark_sky_visibility_1d
      - sensor.dark_sky_visibility_2d
      - sensor.dark_sky_visibility_3d
      - sensor.dark_sky_visibility_4d
      - sensor.dark_sky_visibility_5d
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_wind_bearing_1d
      - sensor.dark_sky_wind_bearing_2d
      - sensor.dark_sky_wind_bearing_3d
      - sensor.dark_sky_wind_bearing_4d
      - sensor.dark_sky_wind_bearing_5d
      - sensor.dark_sky_wind_speed
      - sensor.dark_sky_wind_speed_1d
      - sensor.dark_sky_wind_speed_2d
      - sensor.dark_sky_wind_speed_3d
      - sensor.dark_sky_wind_speed_4d
      - sensor.dark_sky_wind_speed_5d

homekit:
# following two params are now apparently deprecated.
#  auto_start: false
#  safe_mode: false
  filter:
    include_entities:
      - switch.bedroom_reading_lamp
      - binary_sensor.motion_eviesbedroom_occupancy
      - sensor.motion_eviesbedroom_temperature
      - light.masterbedroom1_light
      - light.masterbedroom2_light

influxdb:
  host: 192.168.0.101
  database: homeassistant
  username: homeassistant
  password: !secret influx_password
  
input_boolean:
  boolean_evie_sleep_mode:
    name: boolean indicating whether or not Sleep Mode is on.
  boolean_occupancy_guest_mode:
    name: boolean indicating whether or not Guest Mode is on.

input_datetime:
  datetime_last_alerted_motion_anywhere_unoccupied:
    name: datetime last alert sent for motion detected anywhere, when Unoccupied
    has_date: true
    has_time: true
  datetime_last_alerted_motion_eaves:
    name: datetime last alert sent for motion detected in the Eaves
    has_date: true
    has_time: true

input_select:
  someone_home:
    options:
      - Away
      - Extended Away
      - Just Arrived
      - Just Left
      - Occupied

ios:

logger:
  default: info
  logs:
    custom_components.escea: debug

lovelace:
  mode: yaml

#nest:
#  client_id: !secret nest_client_id
#  client_secret: !secret nest_client_secret

notify:
  - name: petes_ios_devices
    platform: group
    services:
      - service: mobile_app_ipc6kdqxl50gpw
      - service: mobile_app_pete_wills_ipad


person:
  - name: Pete
    id: 9171f88c29f143e9a2a2f5ea2890339d
    device_trackers:
      - device_tracker.pwills_ae34b40a_eba0_46ae_9292_ea520d5db612
      # The other thing is - the app reports when I am on WiFi, so I could just use that as well.
      # I.e. concoct a boolean that shows On/Off depending on whether my Phone is attached to YoP or not.
#      - device_tracker.steve_jobs_iphone_3g
#      - device_tracker.petes_iphone_bt
#      - device_tracker.petes_iphone_gps
#      - device_tracker.petes_iphone_wifi
#      - device_tracker.tile_e4dd14420d344e34
  - name: Emma
    id: 6Y7i2MHyeedbkHT7o$sZ&bPOyk7f1guQ
    device_trackers:
      - device_tracker.emmas_iphone_bt
      - device_tracker.emmas_iphone_wifi

recorder:
  purge_keep_days: 5

# Seemingly roku is now deprecated. Removing.
# TODO: Delete this from the config, assuming this passes.
#roku:
#  - host: 192.168.0.123

# TODO: Need to fix the travis build scripts before I can really go anywhere with this.
#sonoff:
#  username: !secret sonoff_username
#  password: !secret sonoff_password

# Static config of speedtestdotnet is deprecated now, and configured instead through the GUI.
# TODO: Delete this from the config, assuming this passes.

#speedtestdotnet:
#  manual: false
#  scan_interval:
#    hours: 4
#  server_id: 6369


# Broadlink is now completely configured within the GUI.
# I have set the integration within the GUI, and I have commented out this config.
# TODO: Clean below up.
# TODO: i think I have some stranded code for turning on the TV, etc. Not sure. Should check.

#switch:
#  - platform: broadlink
#    # this param is apparently now deprecated.
#    host: !secret broadlink_ip
#    mac: !secret broadlink_mac
#    switches:
#      tv_lg_power:
        # As with most TVs - it's the same IR code for power-on and for power-off,
        # The switch entity's state (I.e. )switch.tv_lg_power) should not be relied on.
        # Rely on "media_player.lg_webos_smart_tv" instead.
        # We are just relying on this to get the TV turned-on in the first place, and from there - use the other entity.
#        friendly_name: "TV Power"
#        command_on:  "JgBYAAABIJMUERMSFDUUERQRFBEUERQRFDUUNRQREzYUNRM2FTQVNRQRExEVEBQ1FRATExISFBEUNRQ2EzYTEhQ5EDUUNRQ1FAAFGAABJ0gUAAxFAAEkSRMADQU="
#        command_off: "JgBYAAABIJMUERMSFDUUERQRFBEUERQRFDUUNRQREzYUNRM2FTQVNRQRExEVEBQ1FRATExISFBEUNRQ2EzYTEhQ5EDUUNRQ1FAAFGAABJ0gUAAxFAAEkSRMADQU="
#      roku_home_button:
        # This button seems to reliably put the Roku into "playing" mode.
#        friendly_name: "Roku Home"
#        command_on: "JgAgAQABIZURFBI4ERQRORETEzcRORI3ERQROREUERQTEhISETkSOBE4ETkRFBEUEhMRFBEUEhMRExEUEjgSNxI4ETkROBE5EgAFKwABJpUSExI4ERQRORETETkRORE4ERQROREUERQRExMSETkRNhQ4EjgRFBEUERQRFBETEjgRFBEUETkROBE5ETgROREUEQAFLAABJpYRExE5ERQRORETEjgRORE5ERMROREUERQRFBEUETgRORE5ETgRFBEUERQRFBEUETgRFBEUETkROBE5ETkROBEUEQAFLQABJZUUERI4EhMTNhMSEzcSOBM2EhMRORMSEhMSExISEjgTNxI3FDYSExITEhMSEhMSEzcSExITEzYTNxM3EjcUNhITEgANBQAAAAAAAAAA"
#        command_off: "JgAgAQABIZURFBI4ERQRORETEzcRORI3ERQROREUERQTEhISETkSOBE4ETkRFBEUEhMRFBEUEhMRExEUEjgSNxI4ETkROBE5EgAFKwABJpUSExI4ERQRORETETkRORE4ERQROREUERQRExMSETkRNhQ4EjgRFBEUERQRFBETEjgRFBEUETkROBE5ETgROREUEQAFLAABJpYRExE5ERQRORETEjgRORE5ERMROREUERQRFBEUETgRORE5ETgRFBEUERQRFBEUETgRFBEUETkROBE5ETkROBEUEQAFLQABJZUUERI4EhMTNhMSEzcSOBM2EhMRORMSEhMSExISEjgTNxI3FDYSExITEhMSEhMSEzcSExITEzYTNxM3EjcUNhITEgANBQAAAAAAAAAA"

tplink:
  discovery: false
  switch:
    - host: 192.168.0.141
    - host: 192.168.0.142

tts:
  - platform: google_translate

weather:
  - platform: darksky
    api_key: !secret bom_api_key
    mode: daily
    latitude: !secret zone_home_lat
    longitude: !secret zone_home_long

webostv:
    host: 192.168.0.121
    #other settings
    turn_on_action:
        service: wake_on_lan.send_magic_packet
        data:
          mac: "00:00:00:00:00:00"

# Includes
automation: !include automations.yaml
group: !include groups.yaml
logbook: !include logbook.yaml
scene old: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
zone: !include zone.yaml
