title: Roscrea
views:
  - title: Home
    path: default_view
    badges:
      - entity: binary_sensor.updater
      - entity: binary_sensor.hallway_downstairs_sensor_motion
      - entity: binary_sensor.storeroom_sensor_motion
      - entity: binary_sensor.evies_bedroom_motion_sensor_1_motion
      - entity: binary_sensor.toilet_sensor_motion
      - entity: binary_sensor.remote_ui
      - entity: sensor.load_15m
      - entity: sensor.disk_use_percent_home
      - entity: sensor.memory_use_percent
      - entity: sensor.swap_use_percent
      - entity: sensor.last_boot
      - entity: sensor.load_1m
      - entity: sensor.load_5m
      - entity: sensor.toilet_sensor_light_level
      - entity: sensor.hallway_downstairs_sensor_light_level
      - entity: sensor.storeroom_sensor_light_level
      - entity: sensor.hallway_downstairs_sensor_temperature
      - entity: sensor.evies_bedroom_motion_sensor_1_light_level
      - entity: sensor.storeroom_sensor_temperature
      - entity: sensor.evies_bedroom_motion_sensor_1_temperature
      - entity: sensor.toilet_sensor_temperature
      - entity: sun.sun
    cards:
      - entity: camera.bom_radar_loop_id_372
        type: picture-entity
      - entities:
          - person.emma_wills
          - person.pete_wills
        title: Presence
        type: entities
      - entities:
          - light.bedroom_evie
          - light.bedroom_guest
          - light.bathroom_downstairs
          - light.hallway_upstairs
          - light.toilet_downstairs
          - light.porch
          - light.laundry
          - light.living_room
          - light.nursery
          - light.entrance_foyer
          - light.storeroom
          - light.rumpus_room
          - light.bedroom_master
          - light.bathroom_upstairs
          - light.entertainment_area_1
          - light.dining_room
          - light.kitchen
          - light.hallway_downstairs
          - light.hue_color_lamp
          - light.hue_white_lamp_4
          - light.hue_white_lamp_11
          - light.hue_white_lamp_1
          - light.hue_white_lamp_5
          - light.hue_color_lamp_2
          - light.hue_white_lamp_9
          - light.hue_white_lamp_2
          - light.hue_white_lamp_6
          - light.hue_white_lamp_12
          - light.hue_white_lamp_8
          - light.exterior_light
          - light.hue_white_lamp_3
          - light.hue_white_lamp_7
          - light.hue_white_lamp_10
          - light.hue_go_1
        title: Light
        type: entities
      - entity: media_player.roku_yl00at185320
        type: media-control
      - entity: media_player.upstairs
        type: media-control
      - entity: media_player.living_room
        type: media-control
      - entity: media_player.kitchen
        type: media-control
      - entities:
          - remote.roku_yl00at185320
        title: Remote
        type: entities
      - entities:
          - switch.kitchen_lighting_strip
          - switch.bedroom_reading_lamp
        title: Switch
        type: entities
      - entity: weather.dark_sky
        type: weather-forecast

  - title: Automations
    cards:
      - entities:
          - automation.porch_light_off_in_the_morning
          - automation.all_downstairs_common_area_lights_to_be_turned_off_at_midnight
          - automation.all_master_bedroom_lights_to_be_turned_off_at_1am_each_morning
          - automation.tv_and_roku_off_at_2am_each_morning
          - automation.porch_light_on_in_the_evening
          - automation.arrival_lights_for_the_first_person_arriving_home_or_any_arrival_after_sunset
          - automation.lights_off_when_the_last_person_leaves_home
        title: Automation
        type: entities
    
  - title: Bedrooms
    cards:
      - entities:
          - light.bedroom_evie
          - sensor.evies_bedroom_motion_sensor_1_temperature
        title: Evie's Bedroom
        type: entities
      - entities:
          - light.hue_white_lamp_9
          - light.hue_white_lamp_11
          - switch.bedroom_reading_lamp
        title: Master Bedroom
        type: entities



