title: Roscrea
views:
  - title: Home
    path: default_view
    cards:
      - entities:
          - sensor.someone_home
          - person.emma
          - person.pete
        show_header_toggle: false
        title: Presence
        type: entities
      - entity: camera.bom_radar_loop_id_372
        type: picture-entity
      - entity: weather.dark_sky
        type: weather-forecast

  - title: Automations
    cards:
      - entities:
          - automation.porch_light_off_in_the_morning
          - automation.all_downstairs_common_area_lights_to_be_turned_off_at_midnight
          - automation.all_master_bedroom_lights_to_be_turned_off_at_1am_each_morning
          - automation.tv_and_roku_off_at_2am_each_morning
          - automation.porch_light_on_in_the_evening
        title: Time-Based Automations
        type: entities
      - entities:
          - automation.arrival_lights_for_the_first_person_arriving_home_or_any_arrival_after_sunset
          - automation.lights_off_when_the_last_person_leaves_home
        title: Presence-Based Automations
        type: entities

  - title: Media
    cards:
      - entities:
        - entity: media_player.roku_yl00at185320
          type: media-control
        - entity: media_player.upstairs
          type: media-control
        - entity: media_player.living_room
          type: media-control
        - entity: media_player.kitchen
          type: media-control
        title: Media
        type: entities

  - title: Bedrooms
    cards:
      - entities:
          - entity: light.bedroom_evie
            name: Ceiling Light
          - entity: sensor.evies_bedroom_motion_sensor_1_temperature
            name: Temperature
        show_header_toggle: false
        title: Evie's Bedroom
        type: entities
      - entities:
          - entity: light.hue_white_lamp_9
            name: Ceiling Light
          - entity: light.hue_white_lamp_11
            name: Standing Lamp
          - entity: switch.bedroom_reading_lamp
            name: Reading Lamp
        show_header_toggle: false
        title: Master Bedroom
        type: entities
      - entities:
          - entity: light.hue_white_lamp_12
            name: Ceiling Light
        show_header_toggle: false
        title: Nursery
        type: entities
      - entities:
          - entity: light.hue_white_lamp_6
            name: South Ceiling Light
          - entity: light.hue_white_lamp_7
            name: North Ceiling Light
        show_header_toggle: false
        title: Rumpus Room
        type: entities

  - title: Nest
    cards:
      - entities:
          - entity: sensor.entrance_foyer_nest_protect_color_status
          - entity: sensor.upstairs_nest_protect_color_status
        show_header_toggle: false
        title: Nest Protects
        type: entities

  - title: System
    cards:
      - entities:
          - sensor.last_boot
          - sensor.disk_use_percent
          - sensor.memory_use_percent
          - sensor.swap_use_percent
          - sensor.processor_use
        show_header_toggle: false
        title: Raspberry Pi
        type: entities
      - entities:
          - sensor.uptime
        show_header_toggle: false
        title: Home Assistant
        type: entities
