title: Roscrea
views:
  - title: Home
    path: default_view
    cards:
      - entities:
          - entity: sensor.someone_home
            name: House Mode
            secondary_info: last-changed
          - entity: person.emma
            secondary_info: last-changed
          - entity: person.pete
            secondary_info: last-changed
        show_header_toggle: false
        title: Presence
        type: entities
      - entity: camera.bom_radar_loop_id_372
        type: picture-entity
      - entity: weather.dark_sky
        type: weather-forecast

  - title: Automations
    cards:
      - entities:
          - automation.porch_light_off_in_the_morning
          - automation.all_downstairs_common_area_lights_to_be_turned_off_at_midnight
          - automation.all_master_bedroom_lights_to_be_turned_off_at_1am_each_morning
          - automation.tv_and_roku_off_at_2am_each_morning
          - automation.hassio_snapshot_daily_at_3am
          - automation.dropbox_backup_sync_daily_at_4am
          - automation.porch_light_on_in_the_evening
        title: Time-Based Automations
        type: entities
      - entities:
          - automation.arrival_lights_for_the_first_person_arriving_home
          - automation.arrival_lights_for_any_arrival_after_sunset_without_regard_to_occupancy
          - automation.lights_off_when_the_last_person_leaves_home
        title: Presence-Based Automations
        type: entities

  - title: Media
    cards:
      - entities:
        - entity: media_player.roku_yl00at185320
          type: media-control
        - entity: media_player.upstairs
          type: media-control
        - entity: media_player.living_room
          type: media-control
        - entity: media_player.kitchen
          type: media-control
        title: Media
        type: entities

  - title: Bedrooms
    cards:
      - entities:
          - entity: light.bedroom_evie
            name: Ceiling Light
          - entity: binary_sensor.evies_bedroom_motion_sensor_1_motion
            name: Motion
            secondary_info: last-changed
          - entity: sensor.evies_bedroom_motion_sensor_1_temperature
            name: Temperature
        show_header_toggle: false
        title: Evie's Bedroom
        type: entities
      - entities:
          - entity: light.hue_white_lamp_9
            name: Ceiling Light
          - entity: light.hue_white_lamp_11
            name: Standing Lamp
          - entity: switch.bedroom_reading_lamp
            name: Reading Lamp
        show_header_toggle: false
        title: Master Bedroom
        type: entities
      - entities:
          - entity: light.hue_white_lamp_12
            name: Ceiling Light
        show_header_toggle: false
        title: Nursery
        type: entities
      - entities:
          - entity: light.hue_white_lamp_6
            name: South Ceiling Light
          - entity: light.hue_white_lamp_7
            name: North Ceiling Light
        show_header_toggle: false
        title: Rumpus Room
        type: entities

  - title: Sensors
    cards:
      - entities:
          - entity: sensor.entrance_foyer_nest_protect_color_status
            name: Entrance Foyer
            secondary_info: last-changed
          - entity: sensor.upstairs_nest_protect_color_status
            name: Upstairs
            secondary_info: last-changed
        show_header_toggle: false
        title: Nest Protects
        type: entities
      - entities:
          - entity: binary_sensor.evies_bedroom_motion_sensor_1_motion
            name: Evie's Bedroom
            secondary_info: last-changed
          - entity: binary_sensor.hallway_downstairs_sensor_motion
            name: Hallway (downstairs)
            secondary_info: last-changed
          - entity: binary_sensor.storeroom_sensor_motion
            name: Storeroom
            secondary_info: last-changed
          - entity: binary_sensor.toilet_sensor_motion
            name: Toilet (downstairs)
            secondary_info: last-changed
        show_header_toggle: false
        title: Motion Detectors
        type: entities

  - title: System
    cards:
      - entities:
          - sensor.last_boot
          - sensor.disk_use_percent
          - sensor.memory_use_percent
          - sensor.swap_use_percent
          - sensor.processor_use
        show_header_toggle: false
        title: Raspberry Pi
        type: entities
      - entities:
          - entity: sensor.samsung_printer
            name: Status
          - entity: sensor.samsung_printer_drum_black
            name: Drum
          - entity: sensor.samsung_printer_toner_black
            name: Toner
          - entity: sensor.samsung_printer_output_tray_0
            name: Tray 0
          - entity: sensor.samsung_printer_tray_1
            name: Tray 1
        show_header_toggle: false
        title: Samsung Printer
        type: entities
      - entities:
          - sensor.uptime
        show_header_toggle: false
        title: Home Assistant
        type: entities
