title: Roscrea
views:
  - title: Home
    path: default_view
    badges:
      - entity: binary_sensor.updater
      - entity: binary_sensor.hallway_downstairs_sensor_motion
      - entity: binary_sensor.storeroom_sensor_motion
      - entity: binary_sensor.evies_bedroom_motion_sensor_1_motion
      - entity: binary_sensor.toilet_sensor_motion
      - entity: binary_sensor.remote_ui
      - entity: sensor.load_15m
      - entity: sensor.disk_use_percent_home
      - entity: sensor.memory_use_percent
      - entity: sensor.swap_use_percent
      - entity: sensor.last_boot
      - entity: sensor.load_1m
      - entity: sensor.load_5m
      - entity: sensor.toilet_sensor_light_level
      - entity: sensor.hallway_downstairs_sensor_light_level
      - entity: sensor.storeroom_sensor_light_level
      - entity: sensor.hallway_downstairs_sensor_temperature
      - entity: sensor.evies_bedroom_motion_sensor_1_light_level
      - entity: sensor.storeroom_sensor_temperature
      - entity: sensor.evies_bedroom_motion_sensor_1_temperature
      - entity: sensor.toilet_sensor_temperature
      - entity: sun.sun
    cards:
      - entities:
          - person.emma_wills
          - person.pete_wills
        show_header_toggle: false
        title: Presence
        type: entities
      - entity: camera.bom_radar_loop_id_372
        type: picture-entity
      - entity: weather.dark_sky
        type: weather-forecast

  - title: Automations
    cards:
      - entities:
          - automation.porch_light_off_in_the_morning
          - automation.all_downstairs_common_area_lights_to_be_turned_off_at_midnight
          - automation.all_master_bedroom_lights_to_be_turned_off_at_1am_each_morning
          - automation.tv_and_roku_off_at_2am_each_morning
          - automation.porch_light_on_in_the_evening
          - automation.arrival_lights_for_the_first_person_arriving_home_or_any_arrival_after_sunset
          - automation.lights_off_when_the_last_person_leaves_home
        title: Automation
        type: entities

  - title: Media
    cards:
      - entities:
        - entity: media_player.roku_yl00at185320
          type: media-control
        - entity: media_player.upstairs
          type: media-control
        - entity: media_player.living_room
          type: media-control
        - entity: media_player.kitchen
          type: media-control
        title: Media
        type: entities

  - title: Bedrooms
    cards:
      - entities:
          - entity: light.bedroom_evie
            name: Ceiling Light
          - entity: sensor.evies_bedroom_motion_sensor_1_temperature
            name: Temperature
        show_header_toggle: false
        title: Evie's Bedroom
        type: entities
      - entities:
          - entity: light.hue_white_lamp_9
            name: Ceiling Light
          - entity: light.hue_white_lamp_11
            name: Tall Lamp
          - entity: switch.bedroom_reading_lamp
            name: Reading Lamp
        show_header_toggle: false
        title: Master Bedroom
        type: entities



