title: Roscrea
views:
  - title: Home
    path: default_view
    cards:
      - entities:
          - entity: sensor.house_mode
            name: House Mode
            secondary_info: last-changed
          - entity: person.emma
            secondary_info: last-changed
          - entity: person.pete
            secondary_info: last-changed
          - entity: input_boolean.boolean_occupancy_guest_mode
            name: Guest Mode
        show_header_toggle: false
        title: Presence
        type: entities
      - type: iframe
        aspect_ratio: 107.626%
        url: http://www.bom.gov.au/radar/IDR762.gif

  - title: Automations
    cards:
      - entities:
          - automation.porch_light_off_in_the_morning
          - automation.all_downstairs_common_area_lights_to_be_turned_off_at_midnight
          - automation.all_master_bedroom_lights_to_be_turned_off_at_1am_each_morning
          - automation.tv_and_roku_off_at_2am_each_morning
          - automation.porch_light_on_in_the_evening
        title: Time-Based Automations
        type: entities
      - entities:
          - automation.arrival_lights_for_the_first_person_arriving_home
          - automation.arrival_lights_for_any_arrival_after_sunset_without_regard_to_occupancy
          - automation.lights_off_when_the_last_person_leaves_home
        title: Presence-Based Automations
        type: entities

  - title: Bedrooms
    cards:
      - entities:
          - entity: light.eviesbedroom_light
            name: Ceiling Light
          - entity: binary_sensor.motion_eviesbedroom_occupancy
            name: Motion
            secondary_info: last-changed
          - entity: sensor.motion_eviesbedroom_temperature
            name: Temperature
          - entity: input_boolean.boolean_evie_sleep_mode
            name: Sleep Mode
        show_header_toggle: false
        title: Evie's Bedroom
        type: entities
      - entities:
          - entity: light.masterbedroom2_light
            name: Ceiling Light
          - entity: light.masterbedroom1_light
            name: Standing Lamp
          - entity: switch.bedroom_reading_lamp
            name: Reading Lamp
        show_header_toggle: false
        title: Master Bedroom
        type: entities
      - entities:
          - entity: light.nursery_light
            name: Ceiling Light
        show_header_toggle: false
        title: Study
        type: entities
      - entities:
          - entity: light.rumpus1_light
            name: South Ceiling Light
          - entity: light.rumpus2_light
            name: North Ceiling Light
        show_header_toggle: false
        title: Rumpus Room
        type: entities

  - title: Media
    cards:
      - entities:
        - entity: media_player.sony_xr_65a80j_3
          name: "Sony Bravia TV"
        show_header_toggle: false
        title: Living Room TV
        type: entities
      - entities:
        - entity: media_player.kitchen
          name: "Kitchen"
        - entity: media_player.living_room
          name: "Living Room"
        - entity: media_player.upstairs
          name: "Upstairs"
        show_header_toggle: false
        title: Sonos
        type: entities

  - title: Sensors
    cards:
      - entities:
          - entity: binary_sensor.door_exterior_front_contact
            name: Front Door
            secondary_info: last-changed
          - entity: binary_sensor.door_exterior_rumpus_contact
            name: Rumpus Room Door
            secondary_info: last-changed
          - entity: binary_sensor.door_exterior_sliding_1_contact
            name: Living Room Glass Door 1
            secondary_info: last-changed
          - entity: binary_sensor.door_exterior_sliding_2_contact
            name: Living Room Glass Door 2
            secondary_info: last-changed
        show_header_toggle: false
        title: External Doors
        type: entities
      - entities:
          - entity: binary_sensor.door_exterior_garage_contact
            name: Store Room
            secondary_info: last-changed
        show_header_toggle: false
        title: Internal Doors
        type: entities
#      - entities:
#          - entity: sensor.entrance_foyer_nest_protect_color_status
#            name: Entrance Foyer
#            secondary_info: last-changed
#          - entity: sensor.upstairs_nest_protect_color_status
#            name: Upstairs
#            secondary_info: last-changed
#        show_header_toggle: false
#        title: Nest Protects
#        type: entities
      - entities:
          - entity: binary_sensor.motion_eaves_occupancy
            name: Eaves
            secondary_info: last-changed
          - entity: binary_sensor.motion_entrancefoyer_occupancy
            name: Entrance Foyer
            secondary_info: last-changed
          - entity: binary_sensor.motion_eviesbedroom_occupancy
            name: Evie's Bedroom
            secondary_info: last-changed
          - entity: binary_sensor.motion_hallwaydownstairs_occupancy
            name: Hallway (downstairs)
            secondary_info: last-changed
          - entity: binary_sensor.motion_storeroom_occupancy
            name: Storeroom
            secondary_info: last-changed
          - entity: binary_sensor.motion_toilet_occupancy
            name: Toilet (downstairs)
            secondary_info: last-changed
        show_header_toggle: false
        title: Motion Detectors
        type: entities

  - title: System
    cards:
      - entities:
          - sensor.last_boot
          - sensor.disk_use_percent
          - sensor.memory_use_percent
          - sensor.swap_use_percent
          - sensor.processor_use
        show_header_toggle: false
        title: Raspberry Pi
        type: entities
      - entities:
          - entity: sensor.speedtest_download
            name: Download
            secondary_info: last-changed
          - entity: sensor.speedtest_upload
            name: Upload
            secondary_info: last-changed
          - entity: sensor.speedtest_ping
            name: Ping
            secondary_info: last-changed
        show_header_toggle: false
        title: Speed Test
        type: entities

#      - entities:
#          - sensor.uptime
#        show_header_toggle: false
#        title: Home Assistant
#        type: entities
