title: Roscrea
views:
  - title: Home
    path: default_view
    badges:
      - entity: binary_sensor.updater
      - entity: binary_sensor.hallway_downstairs_sensor_motion
      - entity: binary_sensor.storeroom_sensor_motion
      - entity: binary_sensor.evies_bedroom_motion_sensor_1_motion
      - entity: binary_sensor.toilet_sensor_motion
      - entity: binary_sensor.remote_ui
      - entity: person.pete_wills
      - entity: device_tracker.1c_36_bb_bd_0c_cb
      - entity: device_tracker.f4_5c_89_3f_60_0e
      - entity: device_tracker.28_ff_3c_4e_c8_23
      - entity: device_tracker.pete_wills_ipad
      - entity: device_tracker.steve_jobs_iphone_3g
      - entity: device_tracker.emma_s_iphone
      - entity: device_tracker.lexon_mino
      - entity: sensor.load_15m
      - entity: sensor.disk_use_percent_home
      - entity: sensor.memory_use_percent
      - entity: sensor.swap_use_percent
      - entity: sensor.last_boot
      - entity: sensor.load_1m
      - entity: sensor.load_5m
      - entity: sensor.geocoded_location
      - entity: sensor.last_update_trigger
      - entity: sensor.bssid
      - entity: sensor.connection_type
      - entity: sensor.activity
      - entity: sensor.sim_1
      - entity: sensor.battery_level
      - entity: sensor.battery_state
      - entity: sensor.ssid
      - entity: sensor.battery_level_2
      - entity: sensor.last_update_trigger_2
      - entity: sensor.average_active_pace
      - entity: sensor.battery_state_2
      - entity: sensor.bssid_2
      - entity: sensor.distance
      - entity: sensor.floors_ascended
      - entity: sensor.connection_type_2
      - entity: sensor.sim_1_2
      - entity: sensor.floors_descended
      - entity: sensor.steps
      - entity: sensor.ssid_2
      - entity: sensor.geocoded_location_2
      - entity: sensor.activity_2
      - entity: sensor.toilet_sensor_light_level
      - entity: sensor.hallway_downstairs_sensor_light_level
      - entity: sensor.storeroom_sensor_light_level
      - entity: sensor.hallway_downstairs_sensor_temperature
      - entity: sensor.evies_bedroom_motion_sensor_1_light_level
      - entity: sensor.storeroom_sensor_temperature
      - entity: sensor.evies_bedroom_motion_sensor_1_temperature
      - entity: sensor.toilet_sensor_temperature
      - entity: sun.sun

  - title: Automations
    path: default_view
    cards:
      - entities:
          - automation.porch_light_off_in_the_morning
          - automation.all_downstairs_common_area_lights_to_be_turned_off_at_midnight
          - automation.all_master_bedroom_lights_to_be_turned_off_at_1am_each_morning
          - automation.tv_and_roku_off_at_2am_each_morning
          - automation.porch_light_on_in_the_evening
          - automation.arrival_lights_for_the_first_person_arriving_home_or_any_arrival_after_sunset
          - automation.lights_off_when_the_last_person_leaves_home
        title: Automation
        type: entities
    
  - title: Bedrooms
    path: default_view


